// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MinerInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerInfo) Reset()         { *m = MinerInfo{} }
func (m *MinerInfo) String() string { return proto.CompactTextString(m) }
func (*MinerInfo) ProtoMessage()    {}
func (*MinerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0}
}

func (m *MinerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerInfo.Unmarshal(m, b)
}
func (m *MinerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerInfo.Marshal(b, m, deterministic)
}
func (m *MinerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerInfo.Merge(m, src)
}
func (m *MinerInfo) XXX_Size() int {
	return xxx_messageInfo_MinerInfo.Size(m)
}
func (m *MinerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MinerInfo proto.InternalMessageInfo

func (m *MinerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ChainInfo struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainInfo) Reset()         { *m = ChainInfo{} }
func (m *ChainInfo) String() string { return proto.CompactTextString(m) }
func (*ChainInfo) ProtoMessage()    {}
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{1}
}

func (m *ChainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInfo.Unmarshal(m, b)
}
func (m *ChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInfo.Marshal(b, m, deterministic)
}
func (m *ChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInfo.Merge(m, src)
}
func (m *ChainInfo) XXX_Size() int {
	return xxx_messageInfo_ChainInfo.Size(m)
}
func (m *ChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInfo proto.InternalMessageInfo

func (m *ChainInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transactions struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{2}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MiningInfo struct {
	Transactions         []byte   `protobuf:"bytes,1,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Miner                string   `protobuf:"bytes,3,opt,name=miner,proto3" json:"miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningInfo) Reset()         { *m = MiningInfo{} }
func (m *MiningInfo) String() string { return proto.CompactTextString(m) }
func (*MiningInfo) ProtoMessage()    {}
func (*MiningInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{3}
}

func (m *MiningInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningInfo.Unmarshal(m, b)
}
func (m *MiningInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningInfo.Marshal(b, m, deterministic)
}
func (m *MiningInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningInfo.Merge(m, src)
}
func (m *MiningInfo) XXX_Size() int {
	return xxx_messageInfo_MiningInfo.Size(m)
}
func (m *MiningInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MiningInfo proto.InternalMessageInfo

func (m *MiningInfo) GetTransactions() []byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *MiningInfo) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *MiningInfo) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

type CheckerInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckerInfo) Reset()         { *m = CheckerInfo{} }
func (m *CheckerInfo) String() string { return proto.CompactTextString(m) }
func (*CheckerInfo) ProtoMessage()    {}
func (*CheckerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{4}
}

func (m *CheckerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckerInfo.Unmarshal(m, b)
}
func (m *CheckerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckerInfo.Marshal(b, m, deterministic)
}
func (m *CheckerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckerInfo.Merge(m, src)
}
func (m *CheckerInfo) XXX_Size() int {
	return xxx_messageInfo_CheckerInfo.Size(m)
}
func (m *CheckerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CheckerInfo proto.InternalMessageInfo

func (m *CheckerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckerInfo) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MinerInfo)(nil), "network.MinerInfo")
	proto.RegisterType((*ChainInfo)(nil), "network.ChainInfo")
	proto.RegisterType((*Transactions)(nil), "network.Transactions")
	proto.RegisterType((*MiningInfo)(nil), "network.MiningInfo")
	proto.RegisterType((*CheckerInfo)(nil), "network.CheckerInfo")
	proto.RegisterType((*Response)(nil), "network.Response")
}

func init() { proto.RegisterFile("network.proto", fileDescriptor_8571034d60397816) }

var fileDescriptor_8571034d60397816 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xbf, 0x4f, 0xfb, 0x30,
	0x10, 0xc5, 0xbf, 0xfe, 0x16, 0x4a, 0x7b, 0x6d, 0x91, 0x30, 0x3f, 0x54, 0x65, 0xa1, 0xf2, 0x94,
	0xa9, 0x42, 0x74, 0x01, 0x21, 0xa6, 0x0e, 0x88, 0xa1, 0x19, 0x5c, 0xc4, 0xc4, 0x62, 0x92, 0x83,
	0x58, 0x6d, 0xcf, 0x55, 0xec, 0x0a, 0xf1, 0x9f, 0x33, 0xa2, 0x38, 0x3f, 0x9a, 0x4a, 0x61, 0xf3,
	0x7b, 0x7a, 0x77, 0xba, 0xf7, 0x91, 0x61, 0x44, 0xe8, 0xbe, 0x4c, 0xb6, 0x9a, 0x6e, 0x33, 0xe3,
	0x0c, 0x3f, 0x29, 0xa5, 0xb8, 0x86, 0xfe, 0x42, 0x13, 0x66, 0xcf, 0xf4, 0x61, 0x38, 0x87, 0x23,
	0x52, 0x1b, 0x1c, 0xb3, 0x09, 0x0b, 0xfb, 0xd2, 0xbf, 0xf3, 0xc0, 0x3c, 0x55, 0x9a, 0xaa, 0x40,
	0xa2, 0x9c, 0xf2, 0x81, 0xa1, 0xf4, 0x6f, 0x21, 0x60, 0xf8, 0x92, 0x29, 0xb2, 0x2a, 0x76, 0xda,
	0x90, 0x6d, 0xcd, 0xbc, 0x01, 0x2c, 0x34, 0x69, 0xfa, 0xf4, 0x5b, 0x04, 0x0c, 0x5d, 0x63, 0xa2,
	0x4c, 0x1e, 0x78, 0xfc, 0x02, 0x8e, 0xc9, 0x50, 0x8c, 0xe3, 0xff, 0x13, 0x16, 0x76, 0x64, 0x21,
	0x72, 0x77, 0x93, 0x5f, 0x3b, 0xee, 0xf8, 0x0b, 0x0b, 0x21, 0xee, 0x61, 0x30, 0x4f, 0x31, 0x5e,
	0xfd, 0xdd, 0x82, 0x5f, 0x41, 0xd7, 0x3a, 0xe5, 0x76, 0xd6, 0xef, 0xeb, 0xc9, 0x52, 0x09, 0x80,
	0x9e, 0x44, 0xbb, 0x35, 0x64, 0xf1, 0xf6, 0x87, 0xc1, 0x20, 0x32, 0x09, 0x46, 0x05, 0x1a, 0x3e,
	0x83, 0xfe, 0xf2, 0x9b, 0x62, 0xdf, 0x9e, 0xf3, 0x69, 0x05, 0xb0, 0xc6, 0x15, 0xec, 0xbd, 0x3d,
	0xa1, 0x07, 0x38, 0x7d, 0x42, 0xd7, 0x00, 0xd2, 0x3a, 0x79, 0x59, 0x7b, 0x07, 0xe8, 0x1e, 0x61,
	0xb0, 0x4c, 0x55, 0x86, 0x12, 0xed, 0x6e, 0xed, 0xf8, 0x79, 0x73, 0xb2, 0x84, 0x17, 0xb4, 0x99,
	0xe2, 0x5f, 0xc8, 0x6e, 0x18, 0xbf, 0x83, 0xd1, 0xab, 0x5a, 0xeb, 0x44, 0x39, 0x8c, 0x0a, 0x5c,
	0x8d, 0x03, 0x6b, 0x3e, 0xc1, 0x59, 0xed, 0x56, 0xd5, 0xdf, 0xbb, 0xfe, 0x57, 0xcc, 0x7e, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x37, 0x46, 0x49, 0xd9, 0x26, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NodeNetworkClient is the client API for NodeNetwork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeNetworkClient interface {
	// blockchainを同期する
	SyncChain(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*ChainInfo, error)
	// トランザクションを取得する
	GetTransaction(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*Transactions, error)
	// 採掘結果を公開する
	ShareResult(ctx context.Context, opts ...grpc.CallOption) (NodeNetwork_ShareResultClient, error)
	// 検証結果を報告
	ValidateNonce(ctx context.Context, in *CheckerInfo, opts ...grpc.CallOption) (*Response, error)
}

type nodeNetworkClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeNetworkClient(cc grpc.ClientConnInterface) NodeNetworkClient {
	return &nodeNetworkClient{cc}
}

func (c *nodeNetworkClient) SyncChain(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*ChainInfo, error) {
	out := new(ChainInfo)
	err := c.cc.Invoke(ctx, "/network.NodeNetwork/SyncChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkClient) GetTransaction(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/network.NodeNetwork/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkClient) ShareResult(ctx context.Context, opts ...grpc.CallOption) (NodeNetwork_ShareResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeNetwork_serviceDesc.Streams[0], "/network.NodeNetwork/ShareResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeNetworkShareResultClient{stream}
	return x, nil
}

type NodeNetwork_ShareResultClient interface {
	Send(*MiningInfo) error
	Recv() (*MiningInfo, error)
	grpc.ClientStream
}

type nodeNetworkShareResultClient struct {
	grpc.ClientStream
}

func (x *nodeNetworkShareResultClient) Send(m *MiningInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeNetworkShareResultClient) Recv() (*MiningInfo, error) {
	m := new(MiningInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodeNetworkClient) ValidateNonce(ctx context.Context, in *CheckerInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/network.NodeNetwork/ValidateNonce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeNetworkServer is the server API for NodeNetwork service.
type NodeNetworkServer interface {
	// blockchainを同期する
	SyncChain(context.Context, *MinerInfo) (*ChainInfo, error)
	// トランザクションを取得する
	GetTransaction(context.Context, *MinerInfo) (*Transactions, error)
	// 採掘結果を公開する
	ShareResult(NodeNetwork_ShareResultServer) error
	// 検証結果を報告
	ValidateNonce(context.Context, *CheckerInfo) (*Response, error)
}

// UnimplementedNodeNetworkServer can be embedded to have forward compatible implementations.
type UnimplementedNodeNetworkServer struct {
}

func (*UnimplementedNodeNetworkServer) SyncChain(ctx context.Context, req *MinerInfo) (*ChainInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncChain not implemented")
}
func (*UnimplementedNodeNetworkServer) GetTransaction(ctx context.Context, req *MinerInfo) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedNodeNetworkServer) ShareResult(srv NodeNetwork_ShareResultServer) error {
	return status.Errorf(codes.Unimplemented, "method ShareResult not implemented")
}
func (*UnimplementedNodeNetworkServer) ValidateNonce(ctx context.Context, req *CheckerInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateNonce not implemented")
}

func RegisterNodeNetworkServer(s *grpc.Server, srv NodeNetworkServer) {
	s.RegisterService(&_NodeNetwork_serviceDesc, srv)
}

func _NodeNetwork_SyncChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServer).SyncChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NodeNetwork/SyncChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServer).SyncChain(ctx, req.(*MinerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetwork_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NodeNetwork/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServer).GetTransaction(ctx, req.(*MinerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetwork_ShareResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeNetworkServer).ShareResult(&nodeNetworkShareResultServer{stream})
}

type NodeNetwork_ShareResultServer interface {
	Send(*MiningInfo) error
	Recv() (*MiningInfo, error)
	grpc.ServerStream
}

type nodeNetworkShareResultServer struct {
	grpc.ServerStream
}

func (x *nodeNetworkShareResultServer) Send(m *MiningInfo) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeNetworkShareResultServer) Recv() (*MiningInfo, error) {
	m := new(MiningInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _NodeNetwork_ValidateNonce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServer).ValidateNonce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NodeNetwork/ValidateNonce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServer).ValidateNonce(ctx, req.(*CheckerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.NodeNetwork",
	HandlerType: (*NodeNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncChain",
			Handler:    _NodeNetwork_SyncChain_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _NodeNetwork_GetTransaction_Handler,
		},
		{
			MethodName: "ValidateNonce",
			Handler:    _NodeNetwork_ValidateNonce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ShareResult",
			Handler:       _NodeNetwork_ShareResult_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "network.proto",
}
