// Code generated by protoc-gen-go. DO NOT EDIT.
// source: network.proto

package network

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MinerInfo struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerInfo) Reset()         { *m = MinerInfo{} }
func (m *MinerInfo) String() string { return proto.CompactTextString(m) }
func (*MinerInfo) ProtoMessage()    {}
func (*MinerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0}
}

func (m *MinerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerInfo.Unmarshal(m, b)
}
func (m *MinerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerInfo.Marshal(b, m, deterministic)
}
func (m *MinerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerInfo.Merge(m, src)
}
func (m *MinerInfo) XXX_Size() int {
	return xxx_messageInfo_MinerInfo.Size(m)
}
func (m *MinerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MinerInfo proto.InternalMessageInfo

func (m *MinerInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ChainInfo struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainInfo) Reset()         { *m = ChainInfo{} }
func (m *ChainInfo) String() string { return proto.CompactTextString(m) }
func (*ChainInfo) ProtoMessage()    {}
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{1}
}

func (m *ChainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInfo.Unmarshal(m, b)
}
func (m *ChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInfo.Marshal(b, m, deterministic)
}
func (m *ChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInfo.Merge(m, src)
}
func (m *ChainInfo) XXX_Size() int {
	return xxx_messageInfo_ChainInfo.Size(m)
}
func (m *ChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInfo proto.InternalMessageInfo

func (m *ChainInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transactions struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{2}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type MiningInfo struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MiningInfo) Reset()         { *m = MiningInfo{} }
func (m *MiningInfo) String() string { return proto.CompactTextString(m) }
func (*MiningInfo) ProtoMessage()    {}
func (*MiningInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{3}
}

func (m *MiningInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MiningInfo.Unmarshal(m, b)
}
func (m *MiningInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MiningInfo.Marshal(b, m, deterministic)
}
func (m *MiningInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiningInfo.Merge(m, src)
}
func (m *MiningInfo) XXX_Size() int {
	return xxx_messageInfo_MiningInfo.Size(m)
}
func (m *MiningInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MiningInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MiningInfo proto.InternalMessageInfo

func (m *MiningInfo) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Broadcast struct {
	Transactions         []byte   `protobuf:"bytes,1,opt,name=transactions,proto3" json:"transactions,omitempty"`
	Nonce                int64    `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Miner                string   `protobuf:"bytes,3,opt,name=miner,proto3" json:"miner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Broadcast) Reset()         { *m = Broadcast{} }
func (m *Broadcast) String() string { return proto.CompactTextString(m) }
func (*Broadcast) ProtoMessage()    {}
func (*Broadcast) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{4}
}

func (m *Broadcast) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broadcast.Unmarshal(m, b)
}
func (m *Broadcast) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broadcast.Marshal(b, m, deterministic)
}
func (m *Broadcast) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broadcast.Merge(m, src)
}
func (m *Broadcast) XXX_Size() int {
	return xxx_messageInfo_Broadcast.Size(m)
}
func (m *Broadcast) XXX_DiscardUnknown() {
	xxx_messageInfo_Broadcast.DiscardUnknown(m)
}

var xxx_messageInfo_Broadcast proto.InternalMessageInfo

func (m *Broadcast) GetTransactions() []byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Broadcast) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Broadcast) GetMiner() string {
	if m != nil {
		return m.Miner
	}
	return ""
}

func init() {
	proto.RegisterType((*MinerInfo)(nil), "network.MinerInfo")
	proto.RegisterType((*ChainInfo)(nil), "network.ChainInfo")
	proto.RegisterType((*Transactions)(nil), "network.Transactions")
	proto.RegisterType((*MiningInfo)(nil), "network.MiningInfo")
	proto.RegisterType((*Broadcast)(nil), "network.Broadcast")
}

func init() { proto.RegisterFile("network.proto", fileDescriptor_8571034d60397816) }

var fileDescriptor_8571034d60397816 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4b, 0x2d, 0x29,
	0xcf, 0x2f, 0xca, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xe4, 0xb9,
	0x38, 0x7d, 0x33, 0xf3, 0x52, 0x8b, 0x3c, 0xf3, 0xd2, 0xf2, 0x85, 0x84, 0xb8, 0x58, 0x52, 0x12,
	0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x90, 0x02, 0xe7, 0x8c, 0xc4,
	0xcc, 0x3c, 0x9c, 0x0a, 0x94, 0xb8, 0x78, 0x42, 0x8a, 0x12, 0xf3, 0x8a, 0x13, 0x93, 0x4b, 0x32,
	0xf3, 0xf3, 0x8a, 0xb1, 0xaa, 0x51, 0xe0, 0xe2, 0xf2, 0xcd, 0xcc, 0xcb, 0xcc, 0x4b, 0xc7, 0x69,
	0x4a, 0x34, 0x17, 0xa7, 0x53, 0x51, 0x7e, 0x62, 0x4a, 0x72, 0x62, 0x71, 0x89, 0x90, 0x12, 0x17,
	0x4f, 0x09, 0x92, 0x91, 0x50, 0x85, 0x28, 0x62, 0x42, 0x22, 0x5c, 0xac, 0x79, 0xf9, 0x79, 0xc9,
	0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x10, 0x0e, 0x48, 0x34, 0x17, 0xe4, 0x1d, 0x09,
	0x66, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0xc7, 0x68, 0x1f, 0x23, 0x17, 0xb7, 0x5f, 0x7e, 0x4a,
	0xaa, 0x1f, 0xc4, 0xd3, 0x42, 0xc6, 0x5c, 0x9c, 0xc1, 0x95, 0x79, 0xc9, 0x60, 0x7f, 0x09, 0x09,
	0xe9, 0xc1, 0x82, 0x06, 0x1e, 0x10, 0x52, 0x08, 0x31, 0x84, 0xdf, 0xad, 0xb9, 0xf8, 0xdc, 0x53,
	0x4b, 0x90, 0xbc, 0x8a, 0x55, 0xa7, 0x28, 0x5c, 0x0c, 0x25, 0x50, 0x6c, 0xb9, 0x78, 0x03, 0x4a,
	0x93, 0x72, 0x32, 0x8b, 0x33, 0x82, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0x08, 0xd8, 0x0a, 0x0f, 0x0a,
	0x25, 0x06, 0x0d, 0x46, 0x03, 0xc6, 0x24, 0x36, 0x70, 0xac, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x74, 0x8e, 0x57, 0xce, 0xc6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NodeNetworkClient is the client API for NodeNetwork service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeNetworkClient interface {
	// blockchainを同期する
	SyncChain(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*ChainInfo, error)
	// トランザクションを取得する
	GetTransaction(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*Transactions, error)
	// 採掘結果を公開する
	PublishResult(ctx context.Context, opts ...grpc.CallOption) (NodeNetwork_PublishResultClient, error)
}

type nodeNetworkClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeNetworkClient(cc grpc.ClientConnInterface) NodeNetworkClient {
	return &nodeNetworkClient{cc}
}

func (c *nodeNetworkClient) SyncChain(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*ChainInfo, error) {
	out := new(ChainInfo)
	err := c.cc.Invoke(ctx, "/network.NodeNetwork/SyncChain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkClient) GetTransaction(ctx context.Context, in *MinerInfo, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/network.NodeNetwork/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeNetworkClient) PublishResult(ctx context.Context, opts ...grpc.CallOption) (NodeNetwork_PublishResultClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodeNetwork_serviceDesc.Streams[0], "/network.NodeNetwork/PublishResult", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodeNetworkPublishResultClient{stream}
	return x, nil
}

type NodeNetwork_PublishResultClient interface {
	Send(*MinerInfo) error
	Recv() (*Broadcast, error)
	grpc.ClientStream
}

type nodeNetworkPublishResultClient struct {
	grpc.ClientStream
}

func (x *nodeNetworkPublishResultClient) Send(m *MinerInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *nodeNetworkPublishResultClient) Recv() (*Broadcast, error) {
	m := new(Broadcast)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NodeNetworkServer is the server API for NodeNetwork service.
type NodeNetworkServer interface {
	// blockchainを同期する
	SyncChain(context.Context, *MinerInfo) (*ChainInfo, error)
	// トランザクションを取得する
	GetTransaction(context.Context, *MinerInfo) (*Transactions, error)
	// 採掘結果を公開する
	PublishResult(NodeNetwork_PublishResultServer) error
}

// UnimplementedNodeNetworkServer can be embedded to have forward compatible implementations.
type UnimplementedNodeNetworkServer struct {
}

func (*UnimplementedNodeNetworkServer) SyncChain(ctx context.Context, req *MinerInfo) (*ChainInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncChain not implemented")
}
func (*UnimplementedNodeNetworkServer) GetTransaction(ctx context.Context, req *MinerInfo) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (*UnimplementedNodeNetworkServer) PublishResult(srv NodeNetwork_PublishResultServer) error {
	return status.Errorf(codes.Unimplemented, "method PublishResult not implemented")
}

func RegisterNodeNetworkServer(s *grpc.Server, srv NodeNetworkServer) {
	s.RegisterService(&_NodeNetwork_serviceDesc, srv)
}

func _NodeNetwork_SyncChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServer).SyncChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NodeNetwork/SyncChain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServer).SyncChain(ctx, req.(*MinerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetwork_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinerInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeNetworkServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.NodeNetwork/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeNetworkServer).GetTransaction(ctx, req.(*MinerInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeNetwork_PublishResult_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeNetworkServer).PublishResult(&nodeNetworkPublishResultServer{stream})
}

type NodeNetwork_PublishResultServer interface {
	Send(*Broadcast) error
	Recv() (*MinerInfo, error)
	grpc.ServerStream
}

type nodeNetworkPublishResultServer struct {
	grpc.ServerStream
}

func (x *nodeNetworkPublishResultServer) Send(m *Broadcast) error {
	return x.ServerStream.SendMsg(m)
}

func (x *nodeNetworkPublishResultServer) Recv() (*MinerInfo, error) {
	m := new(MinerInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _NodeNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.NodeNetwork",
	HandlerType: (*NodeNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncChain",
			Handler:    _NodeNetwork_SyncChain_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _NodeNetwork_GetTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PublishResult",
			Handler:       _NodeNetwork_PublishResult_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "network.proto",
}
